[package]
name = "fundloom_starknet"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.12.2"
openzeppelin = "1.0.0"

[dev-dependencies]
snforge_std = "0.41.0"
assert_macros = "2.12.2"

# [[target.starknet-contract]]
# # Enable the Sierra code generation in the default profile
# disallowed-libfuncs = ["starknet"]
# allowed-libfuncs = ["starknet::starknet_libfunc"]

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
block_id.tag = "latest"

